version: '3'

services:

  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD = yes is recommended only for development.
      - MARIADB_USER=user
      - MARIADB_PASSWORD=dddd
      - MARIADB_ROOT_PASSWORD=dddd
      - MARIADB_DATABASE=project_one
    volumes:
      - ./mariadb:/var/lib/mysql
      # - ./dev/mariadb:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  application:
    image: docker.io/bitnami/laravel:10
    restart: always
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=user
      - DB_DATABASE=project_one
    volumes:
      - './src:/app'
    depends_on:
      - mariadb
